spring.application.name=dept-wise-desig-project
#Database connection build

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=admin

#JPA setup
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
debug=true
